'''Winning Rules as follows :

Rock vs paper-> paper wins
Rock vs scissor-> Rock wins
paper vs scissor-> scissor wins.


            Good luck'''


import random
player = ["""
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
Rock""","""
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
Paper""","""
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
Scissor"""]
ply_input = int(input('Welcome!!  Choose from Rock(0) - Paper(1) - Scissor(2)\n'))
print("----------------Player------------------")
Player_choice = player[ply_input] 
print(Player_choice)


# computer autogenerated choice
print("----------------Computer-----------------")
computer = ["""
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
Rock""","""
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
Paper""","""
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
Scissor"""]
com_length = len(computer)
com_choice = random.randint(0,com_length-1)
print(computer[com_choice])

# Ye mene khud bina kisi ki help ke pehla mushkil project banaya he-----