import turtle as t

tim  = t.Turtle()

# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()
# tim.forward(10)
# tim.penup()
# tim.forward(10)
# tim.pendown()



# You can do this with for loop 
for i in range(15):
    tim.forward(10)
    tim.penup()
    tim.forward(10)
    tim.pendown()